# Generated by Django 4.2.16 on 2026-05-02 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('balanca', 'Balança'), ('syos', 'SYOS'), ('logger', 'Logger'), ('paquimetro', 'Paquímetro'), ('termometro', 'Termômetro Espeto'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('name', models.CharField(max_length=200, verbose_name='Equipamento')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Local')),
                ('model', models.CharField(blank=True, max_length=200, verbose_name='Modelo')),
                ('identification', models.CharField(blank=True, max_length=200, verbose_name='Identificação')),
                ('serial_number', models.CharField(blank=True, max_length=200, verbose_name='N.º Série')),
                ('certificate_number', models.CharField(blank=True, max_length=200, verbose_name='N.º Certificado')),
                ('calibration_frequency_days', models.IntegerField(default=365, verbose_name='Frequência (dias)')),
                ('last_calibration_date', models.DateField(blank=True, null=True, verbose_name='Última Calibração')),
                ('next_calibration_date', models.DateField(blank=True, null=True, verbose_name='Próxima Calibração')),
                ('situation', models.CharField(choices=[('ativo', 'Ativo'), ('danificado', 'Danificado'), ('perdido', 'Perdido'), ('fora_de_uso', 'Fora de Uso')], default='ativo', max_length=20, verbose_name='Situação')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Certificado PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(blank=True, max_length=200, verbose_name='N.º Certificado')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('validity_months', models.IntegerField(default=12, verbose_name='Validade (meses)')),
                ('requestor', models.CharField(blank=True, max_length=500, verbose_name='Solicitante')),
                ('material_type', models.CharField(blank=True, max_length=200, verbose_name='Material')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Fabricante')),
                ('model', models.CharField(blank=True, max_length=200, verbose_name='Modelo')),
                ('serial_number', models.CharField(blank=True, max_length=200, verbose_name='N.º Série')),
                ('identification', models.CharField(blank=True, max_length=200, verbose_name='Identificação')),
                ('measurement_range', models.CharField(blank=True, max_length=200, verbose_name='Faixa de Medição')),
                ('resolution', models.CharField(blank=True, max_length=100, verbose_name='Resolução')),
                ('calibration_status', models.CharField(blank=True, max_length=100, verbose_name='Status Calibração')),
                ('pdf_file', models.FileField(upload_to='certificates/', verbose_name='PDF')),
                ('raw_extracted_text', models.TextField(blank=True, verbose_name='Texto Extraído')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='equipment.equipment')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificado de Calibração',
                'verbose_name_plural': 'Certificados de Calibração',
                'ordering': ['-created_at'],
            },
        ),
    ]
